[package]
name = "manager"
version = "1.0.0"
authors = []

[addresses]
pyth = "0x9357e76fe965c9956a76181ee49f66d51b7f9c3800182a944ed96be86301e49f"
deployer = "0x9236893d6444b208b7e0b3e8d4be4ace90b6d17817ab7d1584e46a33ef5c50c9"
wormhole = "0xa3ad2d9c8114b9a4fe97d45b7a9d3c731148d936b0f5dd396fc20a53a11a70da"
vault = "e24193f1a406f505817f6d16509b738ab35f8e599d34b2a170b07eba46c59880"
std = "0x1"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
[dependencies]
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/aptos/contracts", rev = "main" }

[dev-dependencies]
